name: __AppName__
options:
  bundleIdPrefix: __BundleIdPrefix__
  deploymentTarget:
    iOS: "__DeploymentTarget__"
  xcodeVersion: "26.0.1"

settings:
  base:
    SWIFT_VERSION: "6.2"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

configs:
  Debug Mock: debug
  Debug Dev: debug
  Release Prod: release

targets:
  __AppName__:
    type: application
    platform: iOS
    sources:
      - path: __AppName__
        type: syncedFolder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: __BundleIdPrefix__.__AppName__
        INFOPLIST_FILE: __AppName__/Info.plist
      configs:
        Debug Mock:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) MOCK
        Debug Dev:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) DEV
        Release Prod:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) PROD
    dependencies:
      - package: BurakKit
        product: DependencyContainer
      - package: BurakKit
        product: DynamicColor
      - package: SwiftfulRouting

packages:
  BurakKit:
    url: https://github.com/developerburakgul/BurakKit.git
    from: "0.1.3"
  SwiftfulRouting:
    url: https://github.com/SwiftfulThinking/SwiftfulRouting.git
    from: "6.0.0"

schemes:
  __AppName__-Mock:
    build:
      targets:
        __AppName__: all
    run:
      config: Debug Mock
  __AppName__-Dev:
    build:
      targets:
        __AppName__: all
    run:
      config: Debug Dev
  __AppName__-Prod:
    build:
      targets:
        __AppName__: all
    run:
      config: Release Prod
